# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='stream_link',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='stream',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
