# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-21 18:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stream', '0002_auto_20160505_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
