# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-21 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_stream_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stream',
            old_name='stream_link',
            new_name='out_stream_link',
        ),
        migrations.AddField(
            model_name='stream',
            name='in_stream_link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
