# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-22 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0004_auto_20160621_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='RTSPServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
