# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-22 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0005_rtspserver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
